#!/usr/bin/env python3
"""
Writes electron/core/motionFontMetrics.ts: the advance width of each common
character in the fonts bundled for motion graphics (src/assets/motion-fonts),
so the motion spec compiler can measure text without a canvas. Run it after
adding or changing a font (needs fontTools: pip install fonttools).
"""
import json
import subprocess
from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "src/assets/motion-fonts"
OUT = ROOT / "electron/core/motionFontMetrics.ts"
CHARS = (
	[chr(c) for c in range(32, 127)]
	+ [chr(c) for c in range(160, 256)]
	+ list("–—‘’“”…•€×→←↑↓≈≠≤≥√∞™−")
)

lines = [
	"// Generated by scripts/build-font-metrics.py from src/assets/motion-fonts. Do not edit.",
	"",
	"/** The characters measured, in the order of each font's widths. */",
	f"export const METRIC_CHARS = {json.dumps(''.join(CHARS), ensure_ascii=False)};",
	"",
	"/**",
	" * Per font: cap height and each character's advance width, in thousandths of",
	" * the font size (-1: the font has no such character).",
	" */",
	"export const FONT_METRICS: Record<string, { cap: number; widths: number[] }> = {",
]
for file in sorted(FONTS.glob("*.ttf")):
	font = TTFont(file)
	upm = font["head"].unitsPerEm
	cmap = font.getBestCmap()
	hmtx = font["hmtx"]
	widths = []
	for ch in CHARS:
		glyph = cmap.get(ord(ch))
		widths.append(round(hmtx[glyph][0] * 1000 / upm) if glyph else -1)
	cap = round(font["OS/2"].sCapHeight * 1000 / upm)
	lines.append(f'\t"{file.stem}": {{')
	lines.append(f"\t\tcap: {cap},")
	lines.append(f"\t\twidths: [{', '.join(map(str, widths))}],")
	lines.append("\t},")
lines.append("};")
OUT.write_text("\n".join(lines) + "\n")
# In the repository's own format.
subprocess.run(["npx", "biome", "format", "--write", str(OUT)], cwd=ROOT, check=True, capture_output=True)
print(f"{OUT.relative_to(ROOT)}: {len(CHARS)} characters")
